// AtlSvcApc.idl: AtlSvcApc의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AtlSvcApc.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(ad13b91c-2163-4c4f-8cf3-60d113873001),
	version(1.0),
]
library AtlSvcApcLib
{
	importlib("stdole2.tlb");
};

