// AtlSvcAuth.idl: AtlSvcAuth의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AtlSvcAuth.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(bbb37042-1d80-4585-b705-90ca8288df92),
	version(1.0),
]
library AtlSvcAuthLib
{
	importlib("stdole2.tlb");
};

