// AtlSvcMmf.idl: AtlSvcMmf의 IDL 소스
//

// 이 파일은 MIDL 도구에 의해 처리되어
// 형식 라이브러리(AtlSvcMmf.tlb) 및 마샬링 코드를 생성합니다.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(e642802e-d1af-4aae-950e-b9bf7f53d360),
	version(1.0),
]
library AtlSvcMmfLib
{
	importlib("stdole2.tlb");
};

